const colors = ["#E4B363", "#A3E6BA", "#EF6461"];
const rewards = [
  {
    id: 1,
    name: "plastic-bottle",
    img: "http://dummyimage.com/100x100.png/cc0000/ffffff",
    level: 2,
    color: colors[0],
  },
  {
    id: 2,
    name: "paper",
    img: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    level: 7,
    color: colors[0],
  },
  {
    id: 3,
    name: "paper",
    img: "http://dummyimage.com/100x100.png/dddddd/000000",
    level: 9,
    color: colors[0],
  },
  {
    id: 4,
    name: "glass-bottle",
    img: "http://dummyimage.com/100x100.png/ff4444/ffffff",
    level: 10,
    color: colors[0],
  },
  {
    id: 5,
    name: "can-metal",
    img: "http://dummyimage.com/100x100.png/ff4444/ffffff",
    level: 6,
    color: colors[0],
  },
  {
    id: 6,
    name: "plastic-bottle",
    img: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    level: 5,
    color: colors[0],
  },
  {
    id: 7,
    name: "glass-bottle",
    img: "http://dummyimage.com/100x100.png/cc0000/ffffff",
    level: 4,
    color: colors[0],
  },
  {
    id: 8,
    name: "plastic-bottle",
    img: "http://dummyimage.com/100x100.png/ff4444/ffffff",
    level: 7,
    color: colors[0],
  },
  {
    id: 9,
    name: "can-metal",
    img: "http://dummyimage.com/100x100.png/ff4444/ffffff",
    level: 1,
    color: colors[0],
  },
  {
    id: 10,
    name: "plastic-bottle",
    img: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    level: 7,
    color: colors[0],
  },
  {
    id: 11,
    name: "paper",
    img: "http://dummyimage.com/100x100.png/cc0000/ffffff",
    level: 4,
    color: colors[0],
  },
  {
    id: 12,
    name: "can-metal",
    img: "http://dummyimage.com/100x100.png/cc0000/ffffff",
    level: 5,
    color: colors[0],
  },
  {
    id: 13,
    name: "can-metal",
    img: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    level: 10,
    color: colors[2],
  },
  {
    id: 14,
    name: "plastic-bottle",
    img: "http://dummyimage.com/100x100.png/ff4444/ffffff",
    level: 9,
    color: colors[1],
  },
  {
    id: 15,
    name: "can-metal",
    img: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    level: 6,
    color: colors[0],
  },
  {
    id: 16,
    name: "paper",
    img: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    level: 3,
    color: colors[2],
  },
  {
    id: 17,
    name: "glass-bottle",
    img: "http://dummyimage.com/100x100.png/dddddd/000000",
    level: 1,
    color: colors[1],
  },
  {
    id: 18,
    name: "can-metal",
    img: "http://dummyimage.com/100x100.png/ff4444/ffffff",
    level: 7,
    color: colors[0],
  },
  {
    id: 19,
    name: "metal",
    img: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    level: 5,
    color: colors[2],
  },
  {
    id: 20,
    name: "paper",
    img: "http://dummyimage.com/100x100.png/ff4444/ffffff",
    level: 9,
    color: colors[1],
  },
  {
    id: 21,
    name: "paper",
    img: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    level: 5,
    color: colors[0],
  },
  {
    id: 22,
    name: "plastic-bottle",
    img: "http://dummyimage.com/100x100.png/cc0000/ffffff",
    level: 7,
    color: colors[2],
  },
  {
    id: 23,
    name: "glass-bottle",
    img: "http://dummyimage.com/100x100.png/dddddd/000000",
    level: 2,
    color: colors[1],
  },
  {
    id: 24,
    name: "metal",
    img: "http://dummyimage.com/100x100.png/dddddd/000000",
    level: 4,
    color: colors[0],
  },
  {
    id: 25,
    name: "metal",
    img: "http://dummyimage.com/100x100.png/ff4444/ffffff",
    level: 1,
    color: colors[2],
  },
  {
    id: 26,
    name: "metal",
    img: "http://dummyimage.com/100x100.png/cc0000/ffffff",
    level: 9,
    color: colors[1],
  },
  {
    id: 27,
    name: "glass-bottle",
    img: "http://dummyimage.com/70x70.png/dddddd/000000",
    level: 7,
    color: colors[0],
  },
  {
    id: 28,
    name: "metal",
    img: "http://dummyimage.com/70x70.png/ff4444/ffffff",
    level: 5,
    color: colors[2],
  },
  {
    id: 29,
    name: "paper",
    img: "http://dummyimage.com/70x70.png/5fa2dd/ffffff",
    level: 2,
    color: colors[1],
  },
  {
    id: 30,
    name: "plastic-bottle",
    img: "http://dummyimage.com/70x70.png/cc0000/ffffff",
    level: 6,
    color: colors[0],
  },
];

export default rewards;
