import imageVerre from "../../assets/img/verre.png";
import imageMetal from "../../assets/img/metal.png";
import imageCarton from "../../assets/img/carton.png";
import imageEau from "../../assets/img/eau.png";

const colors = ["#E4B363", "#A3E6BA", "#EF6461"];

const rewards = [
  {
    id: 1,
    name: "plastic-bottle",
    img: imageVerre,
    level: 2,
    color: colors[0],
  },
  {
    id: 2,
    name: "paper",
    img: imageMetal,
    level: 7,
    color: colors[0],
  },
  {
    id: 3,
    name: "paper",
    img: imageEau,
    level: 9,
    color: colors[0],
  },
  {
    id: 4,
    name: "glass-bottle",
    img: imageVerre,
    level: 10,
    color: colors[0],
  },
  {
    id: 5,
    name: "can-metal",
    img: imageCarton,
    level: 6,
    color: colors[0],
  },
  {
    id: 6,
    name: "plastic-bottle",
    img: imageEau,
    level: 5,
    color: colors[0],
  },
  {
    id: 7,
    name: "glass-bottle",
    img: imageMetal,
    level: 4,
    color: colors[0],
  },
  {
    id: 8,
    name: "plastic-bottle",
    img: imageEau,
    level: 7,
    color: colors[0],
  },
  {
    id: 9,
    name: "can-metal",
    img: imageMetal,
    level: 1,
    color: colors[0],
  },
  {
    id: 10,
    name: "plastic-bottle",
    img: imageCarton,
    level: 7,
    color: colors[0],
  },
  {
    id: 11,
    name: "paper",
    img: imageEau,
    level: 4,
    color: colors[0],
  },
  {
    id: 12,
    name: "can-metal",
    img: imageVerre,
    level: 5,
    color: colors[0],
  },
  {
    id: 13,
    name: "can-metal",
    img: imageVerre,
    level: 10,
    color: colors[2],
  },
  {
    id: 14,
    name: "plastic-bottle",
    img: imageMetal,
    level: 9,
    color: colors[1],
  },
  {
    id: 15,
    name: "can-metal",
    img: imageCarton,
    level: 6,
    color: colors[0],
  },
  {
    id: 16,
    name: "paper",
    img: imageVerre,
    level: 3,
    color: colors[2],
  },
  {
    id: 17,
    name: "glass-bottle",
    img: imageCarton,
    level: 1,
    color: colors[1],
  },
  {
    id: 18,
    name: "can-metal",
    img: imageEau,
    level: 7,
    color: colors[0],
  },
  {
    id: 19,
    name: "metal",
    img: imageMetal,
    level: 5,
    color: colors[2],
  },
  {
    id: 20,
    name: "paper",
    img: imageMetal,
    level: 9,
    color: colors[1],
  },
  {
    id: 21,
    name: "paper",
    img: imageVerre,
    level: 5,
    color: colors[0],
  },
  {
    id: 22,
    name: "plastic-bottle",
    img: imageEau,
    level: 7,
    color: colors[2],
  },
  {
    id: 23,
    name: "glass-bottle",
    img: imageCarton,
    level: 2,
    color: colors[1],
  },
  {
    id: 24,
    name: "metal",
    img: imageVerre,
    level: 4,
    color: colors[0],
  },
  {
    id: 25,
    name: "metal",
    img: imageMetal,
    level: 1,
    color: colors[2],
  },
  {
    id: 26,
    name: "metal",
    img: imageCarton,
    level: 9,
    color: colors[1],
  },
  {
    id: 27,
    name: "glass-bottle",
    img: imageEau,
    level: 7,
    color: colors[0],
  },
  {
    id: 28,
    name: "metal",
    img: imageVerre,
    level: 5,
    color: colors[2],
  },
  {
    id: 29,
    name: "paper",
    img: imageEau,
    level: 2,
    color: colors[1],
  },
  {
    id: 30,
    name: "plastic-bottle",
    img: imageVerre,
    level: 6,
    color: colors[0],
  },
];

export default rewards;
